server:
  port: 8081

logging:
  level:
    org.springframework.ai: DEBUG

spring:
  application:
    name: open-ai-mcp-server
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://api.openai.com  #https://api.openai.com/v1
      chat:
        model: gpt-3.5-turbo #gpt-4o-mini
        # or gpt-3.5-turbo-0613 for function calling support